name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      -  uses: actions/checkout@v3
      -  name: build
         run: docker build . --file Dockerfile --tag liatrio
     
      -  name: run image
         run: docker run --rm -d --init -p 80:80 liatrio
      
      -  name: test
         uses: liatrio/github-actions/apprentice-action@master
       
      -  name: docker login
         env:
           DOCKER_USER: ${{secrets.DOCKER_USER}}
           DOCKER_PASS: ${{secrets.DOCKER_PASS}}
         run: |
           docker login -u $DOCKER_USER -p $DOCKER_PASS
           
      -  name: docker push
         run: docker push ${{secrets.DOCKER_USER}}/liatrio_takehome
         
         
      
         
         
         
#   test:
#      needs: build
#      name: run image and tests
#      runs-on: ubuntu-latest
     
#      steps:
#       -  uses: actions/checkout@v3
#       -  name: docker login
#          env:
#            DOCKER_USER: ${{secrets.DOCKER_USER}}
#            DOCKER_PASS: ${{secrets.DOCKER_PASS}}
#          run: |
#            docker login -u $DOCKER_USER -p $DOCKER_PASS
#       -  name: run image
#          run: docker run --rm -d --init -p 80:80 kburns98/liatrio-takehome
#       -  name: run tests   
#          uses: liatrio/github-actions/apprentice-action@master
         
#       -  name: run tests
#          uses: liatrio/github-actions/apprentice-action@master

           
      
     
#   Run:
#     name: run image
#     runs-on: ubuntu-latest
#     steps:
#       -  uses: docker/build-push-action@v2
#          with:
#            tags: test-image:latest
#            push: false
#       -  uses: addnab/docker-run-action@v3
#          with: 
#            image: test-image:latest
#            run: echo "running"
      
#   test: 
#     name: run tests
#     runs-on: ubuntu-latest
    
    
#     steps:
#        -  uses: liatrio/github-actions/apprentice-action@master
       
      

