name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build the Docker image
    runs-on: ubuntu-latest

    steps:
     -  uses: actions/checkout@v3
     -  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
  test: 
    name: run tests
    runs-on: ubuntu-latest
    
    steps:
       -  uses: liatrio/github-actions/apprentice-action@master
       
      

